### ISSUE TITLE
ちょっと気になったところ

### ISSUE THREAD

**Issue by yarikomiVR** [satouyuuki/skillsheet#1]
# 全体的に
**強調**、をもっと使うと文章にメリハリが出て読みやすいですね

# 基本情報
birth ⇒ age

# 転職
個人で調べるには限界があるためバックエンドの開発を経験したく
⇒　これは取る側からしてマイナスなイメージがあると思うので、もうちょっと文言を変えたほうがいいと思います。ex. フロントサイドで得た知識や経験を活かせるバックエンドに挑戦したく......

# 実務経歴
webデザインの経験があるのであれば、サンプル等を張り付けたほうが説得力がでますね。作った中から自信のあるデザインのリンクやスクショを貼ってみてはどうでしょう？

# 自己PR
こ、これは読みにくいです.......
改行や箇条書きを入れないと最後まで読まないです。もったいない。

**Comment by satouyuuki** [comment]
## ご確認と添削してくださりありがとうございます

強調と改行などを取り入れて、より読みやすいように修正しました。
あと読みやすい文章の例なども添えていただき大変参考になりました。

成果物に載せられそうなものがまだ無いのが残念ですが、順次そう言ったものはリンクを貼り付けたりサンプル画像を貼り付けたりします。
